name: Run Tests

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python tests
      run: |
        pytest tests/test_fetch_versions.py -v

  shell-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local
    
    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
        chmod +x tests/*.bats
    
    - name: Run check-release tests
      run: bats tests/test_check_release.bats
    
    - name: Run build scripts tests
      run: bats tests/test_build_scripts.bats

  workflow-tests:
    runs-on: ubuntu-latest
    needs: [python-tests, shell-tests]
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate workflow files
      run: |
        for file in .github/workflows/*.yml
        do
          if [ "$file" != ".github/workflows/tests.yml" ]; then
            echo "Validating $file..."
            cat "$file" | python -c "import yaml, sys; yaml.safe_load(sys.stdin)" || exit 1
          fi
        done